apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skyradar
  namespace: skyradar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skyradar
  minReplicas: 1
  maxReplicas: 3          # teto baixo — app stateless e leve
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
